# About
module: ThemeKit
author: Paw Inc.
author_url: https://paw.cloud
readme: README.md
copyright: '© 2016 [Paw](https://paw.cloud) under [MIT License](https://github.com/luckymarmot/ThemeKit/blob/master/LICENSE).'

# URLs
github_url: https://github.com/luckymarmot/ThemeKit
root_url: https://paw.cloud/opensource/themekit/docs
github_file_prefix: https://github.com/luckymarmot/ThemeKit

# Generation
clean: true
output: Docs
min_acl: public
hide_documentation_coverage: true
skip_undocumented: true
exclude:
  - "Demo*/*.*"
  - "**/*ObjC.swift"
  - "**/*ObjectiveC.swift"
  - "**/NSDictionary+UserTheme.swift"

# Navigation
custom_categories:
  - name: ThemeKit
    children:    
    - ThemeKit
    - Notification
  - name: Themes
    children:    
    - Theme
    - LightTheme
    - DarkTheme
    - SystemTheme
    - UserTheme
  - name: Theme Assets
    children:    
    - ThemeColor
    - ThemeGradient 
    - ThemeImage
# "skip_undocumented: true" side-effect bug: will not document NS* extensions
#   - name: Extensions
#     children:
#     - NSWindow
#     - NSColor
